apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag4-aug1-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rag4-aug1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/rag4-aug1-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
