---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag4-aug1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag4-aug1 
  name: rag4-aug1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi